[package]
name = "lints"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
# dylib:  Rust ABI Linux .so format, compiler plugin required
# cdylib: C    ABI Linux .so format
crate-type=["rlib", "dylib"]

[package.metadata.rust-analyzer]
rustc_private = true
